apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-webcolor
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: / #Esta anotação instrui o controlador NGINX a reescrever o caminho do URL para / antes de encaminhar a solicitação ao serviço backend. Isso é útil para que os serviços backend não precisem lidar com os caminhos completos.
spec:
  ingressClassName: nginx #Indica que o controlador NGINX gerenciará este Ingress.
  rules:
    - http: #Define as regras de roteamento baseadas em caminhos HTTP
        paths: # Rota /blue: Solicitações feitas para <Ingress-IP>/blue são encaminhadas para o serviço service-webcolor-blue na porta 80.
          - path: /blue #As solicitações com caminho que começam com /blue serão roteadas para o serviço especificado.
            pathType: Prefix #Indica que o caminho deve corresponder a um prefixo no URL.
            backend:
              service:
                name: service-webcolor-blue #O tráfego será encaminhado para o serviço chamado service-webcolor-blue
                port: 
                  number: 80
          - path: /green # Rota /green: Solicitações feitas para <Ingress-IP>/green são encaminhadas para o serviço service-webcolor-green na porta 80.
            pathType: Prefix
            backend:
              service:
                name: service-webcolor-green
                port: 
                  number: 80



