apiVersion: v1
kind: LimitRange
metadata: 
  name: limitranger-container
spec:
  limits:
    - type: Container
      max: 
        cpu: 250m
        memory: 250M
      min: 
        cpu: 100m
        memory: 100M